### ISSUE TITLE
parameter 관련해 질문이 있습니다

### ISSUE THREAD

**Issue by JminJ** [haven-jeon/KoBART-chatbot#4]
코드의 구조를 본 다음 학습을 돌려볼 생각인데 argparse에 인자를 넣을때 pl.Trainer.add_argparse_args에는 어떤 parameter들이 들어가야 하는지 궁금해 issue를 적습니다.

글 읽어주셔서 감사합니다 :)

**Comment by haven-jeon** [comment]
`python kobart_chit_chat.py  --help`를  해보시면 리스팅 보이실 겁니다.

**Comment by JminJ** [comment]
답변 감사합니다!

**Comment by haven-jeon** [comment]
해당 이슈는 클로즈 하겠습니다.
