### ISSUE TITLE
hparams 에서 입력 부분에서 attributerror가 납니다 제시된 방법과 동일한데 이유를 모르겠습니다.

### ISSUE THREAD

**Issue by eastjin218** [haven-jeon/KoBART-chatbot#5]
![image](https://user-images.githubusercontent.com/59238298/120273566-a2d57a00-c2e9-11eb-90be-9e6aa26228cb.png)
제시된 방법과 동일하게 진행하는데 error가 발생하였는데 어떻게 확인을 해야할지 몰라서 문의 드립니다.

**Comment by FENRlR** [comment]
`self.hparams = hparams`를

`self.save_hyperparameters(hparams)`로 바꿔보세요

**Comment by haven-jeon** [comment]
PyTorch Lightning 버전이 맞지 않아서 입니다. 
맞는 버전이 인스톨 되게 README.md를 업데이트 했습니다. 701daaa8252eaf4b0381e4d0c0ddba74e45e6a0b

**Comment by haven-jeon** [comment]
해당 이슈 클로즈 하겠습니다. 감사합니다.
